current-wtheme: billarch
current-wwallpaper: ~/.config/billarch/wallpapers/42.png
current-xtheme: billarch
current-xwallpaper: ~/.config/billarch/wallpapers/42.png
custom-wallpapers:
  - ~/.config/billarch/wallpapers/archlinux.png

themes:
  catppuccin-latte:
    available_wallpapers:
      - ~/.config/billarch/wallpapers/archlinux.png
  catppuccin-mocha:
    available_wallpapers:
      - ~/.config/billarch/wallpapers/archlinux.png
  billarch:
    available_wallpapers:
      - ~/.config/billarch/wallpapers/archlinux.png
